### ISSUE TITLE
Webkit Crashes on first time load

### ISSUE THREAD

**Issue by montezumaameya** [WebsiteBeaver/capacitor-document-scanner#12]
I am using 
Ionic Angular - 6
Capacitor - 4

When opening camera, the plugin crashes the first time with following error

java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.imgcodecs.Imgcodecs.imread_1(java.lang.String) (tried Java_org_opencv_imgcodecs_Imgcodecs_imread_11 and Java_org_opencv_imgcodecs_Imgcodecs_imread_11__Ljava_lang_String_2)
	at org.opencv.imgcodecs.Imgcodecs.imread_1(Native Method)
	at org.opencv.imgcodecs.Imgcodecs.imread(Imgcodecs.java:114)
	at com.websitebeaver.documentscanner.utils.ImageUtil.getImageFromFilePath(ImageUtil.kt:32)
	at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerActivity.kt:81)
	at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerActivity.kt:68)
	at com.websitebeaver.documentscanner.utils.CameraUtil.startForResult$lambda-0(CameraUtil.kt:41)
	at com.websitebeaver.documentscanner.utils.CameraUtil.$r8$lambda$QtmUm3JcXlX2aa1YkJnrPoMUzS8(Unknown Source:0)
	at com.websitebeaver.documentscanner.utils.CameraUtil$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:409)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:366)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:712)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:140)
	at android.app.Activity.dispatchActivityResult(Activity.java:8551)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5455)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4904)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4950)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**Comment by montezumaameya** [comment]
any updates on this?

**Comment by dmarcs** [comment]
I created a project using ionic and angular, and I can't reproduce this error.

@capacitor/core 4.6.1
@ionic/angular ^6.1.9

**Comment by montezumaameya** [comment]
Getting this error on redmi devices. Tested this on below device.
Redmi Note 9 Pro

**Comment by dmarcs** [comment]
It worked for me on my Google Pixel 4a. Try creating a new project, and only add this plugin. I wonder if another plugin is interfering.
